/**
 * Recommendation engine type definitions
 */

/**
 * Types of recommendations that can be generated
 */
export type RecommendationType =
  | 'BALANCE_TRANSFER'
  | 'PREPAYMENT'
  | 'REDUCE_TENURE'
  | 'REDUCE_EMI'
  | 'NO_ACTION';

/**
 * Recommendation generated by the engine
 */
export interface Recommendation {
  /** Type of recommendation */
  type: RecommendationType;
  /** Short title for the recommendation */
  title: string;
  /** Detailed description explaining the recommendation */
  description: string;
  /** Estimated savings amount (in rupees) */
  estimatedSavings: number;
  /** Reason why this recommendation was made */
  reason: string;
  /** Confidence score (0-100) indicating recommendation strength */
  confidenceScore: number;
}

// Made with Bob
